### ISSUE TITLE
Attach backend

### ISSUE THREAD

**Issue by CupofJosiah** [CS340-Database-Beavers/cs340-dbb-step4#12]
The SQL queries need to be attached to an OSU mySQL. As of now I can attach it to mine since I am running on my account on the flip servers. The biggest issue will be converting the sql tables to json, as it might be difficult to interact with them directly.

**Comment by nairnhoc** [comment]
I can attach the queries to my mySQL. Regarding converting the tables though, I'm not sure what the best approach would be

**Comment by CupofJosiah** [comment]
Go ahead and fill in your info to db-connector.js then. I'll start experimenting with it

**Comment by nairnhoc** [comment]
Can do; info should be replaced now

**Comment by CupofJosiah** [comment]
READ works with backend attached now!
![image](https://github.com/CS340-Database-Beavers/cs340-dbb-step4/assets/29244571/6658836a-d80b-45e5-a095-2f13d76d7df4)

**Comment by CupofJosiah** [comment]
Create now works with backend attached

**Comment by CupofJosiah** [comment]
Update and Delete now work with backend!
