### ISSUE TITLE
Add ability to terminate employee

### ISSUE THREAD

**Issue by CupofJosiah** [CS340-Database-Beavers/cs340-dbb-step4#20]
Instead of delete

**Comment by nairnhoc** [comment]
We can model terminating an employee (marking as inactive) with this query
```
UPDATE employees SET is_active=0 
WHERE employee_id=%%employee_id%%;
```

**Comment by nairnhoc** [comment]
Were you thinking of a more precise way to check an employee's status, specifically checking if an employee had been fired? I can see how the "is_active" field is a bit of a "catch-all" system - "inactive" could mean a number of things from out sick, to on sabbatical, to fired, to quit the company.

**Comment by CupofJosiah** [comment]
I like that, lets implement that in the next step
