### ISSUE TITLE
Add more data validation

### ISSUE THREAD

**Issue by CupofJosiah** [CS340-Database-Beavers/cs340-dbb-step4#29]
Including turning booleans into 1 and 0, checking for numbers formats, etc.

**Comment by nairnhoc** [comment]
Additional CHECKS have now been added to the tables in DDL.sql:

- Checks the dates of entries to ensure they are in the correct syntax (eg, `hire_date = "hello world"` will now throw error)
- Checks the dates of entries to ensure they logically make sense (eg, `employee.birthday` must be before `employee.hiredate`)
- Checks to make sure the names of roles are correctly formatted (must be composed of 1+ letters [a-z] | [A-Z])
- Checks to make sure the names of projects are correctly formatted (must be composed of 1+ letters [a-z] | [A-Z] and can end with 0+ numbers in the range of [0-9])
- Checks haven't been implemented for the attribute `is_active` in employees (will be replaced with FK to entries in new table `employee_statuses` )
