### ISSUE TITLE
Define a Trigger (Extra Credit)

### ISSUE THREAD

**Issue by CupofJosiah** [CS340-Database-Beavers/cs340-dbb-step4#32]
Using your current CS340 project, define a use-case for a trigger in your database. This use-case can be based on a fictional (but somewhat reasonable) business rule derived from your project outline. Furthermore, the business rule should not be one that is easily enforced using basic constraints (including CHECK constraints). This means that your Trigger should be used for something somewhat complex like,

Modifying a record's data on insert (for example, making sure that inputs are stripped of certain characters)
Validating data based on other records (for example, making sure that an artist cannot have a record released before their birth date)
Modifying a different record's data on an INSERT/DELETE/UPDATE
If you are unsure whether a Trigger could be implemented as a CHECK constraint, try writing it as a CHECK constraint first. If it is not trivial to implement using CHECK (or other simple constraints, see https://mariadb.com/kb/en/constraint/), then its likely a good candidate for a Trigger.

 

Submit a PDF containing the following:

Your group name and your members (at the top)
The business rule (a sentence or two is fine)
The Trigger code you wrote to enforce the business rule (a screen shot works; you can also paste formatted code into the document--just make sure it is readable)
An example of the Trigger working
Provide any necessary setup. This includes your database's state prior to the statement that activates your Trigger. For example, if your trigger depends on the existence of other records besides the one you are updating/inserting/deleting, then those other records should be mentioned.
The statement used to activate the Trigger.
A screen shot that shows the Trigger's effect (this could be an error message--if your Trigger prevents the INSERT/DELETE/UPDATE--or any affected record(s)).

**Comment by CupofJosiah** [comment]
I believe we already fulfill this, but adding the issue so we remember to get points for it

**Comment by nairnhoc** [comment]
Successfully created a trigger for ensuring entries from `salaries` can be deleted without compromising employee's salary histories:
```
DROP TRIGGER IF EXISTS delete_within_the_month;
DELIMITER $$
CREATE TRIGGER delete_within_the_month
BEFORE DELETE ON salaries
  FOR EACH ROW 
    BEGIN
      IF YEAR(OLD.effective_date)*12 + MONTH(OLD.effective_date) < YEAR(CURRENT_DATE())*12 + MONTH(CURRENT_DATE()) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'err: cannot delete a salary outside current month';
      END IF;
    END; $$
DELIMITER ;
```
