### ISSUE TITLE
Maybe remove delete from Employee table

### ISSUE THREAD

**Issue by CupofJosiah** [CS340-Database-Beavers/cs340-dbb-step4#36]
"I expected the remove button to remove from the list, but it only changes the status name to fired. Seems to works as intended. However deleting newly made employee roles seems to work fine as long as you remember to refresh the page after you press it."

**Comment by nairnhoc** [comment]
Maybe we could reword it from "Remove" to "Fire" to make it more intuitive? This would involve creating another template in `views/partials`, but it may resolve the confusion while still mostly maintaining the table's form & allowing the user/admin the ability to easily fire someone.
I've pushed this idea to the repo, but we can always undo it if we want to go another direction
