### ISSUE TITLE
Determine how to handle foreign keys in the UI

### ISSUE THREAD

**Issue by CupofJosiah** [CS340-Database-Beavers/cs340-dbb-step4#4]
Current plan is to convert foreign keys to their associated name. Open to other ideas such as keeping just the foreign key or displaying both.

**Comment by nairnhoc** [comment]
Converting the FKs to their associated name sounds like a good approach, but displaying both the FK id and its associated name might be best since it is possible for employees to have identical first/last names

**Comment by CupofJosiah** [comment]
Started to implement this, it is more difficult than I thought. I'll have to work on this for step 5

**Comment by CupofJosiah** [comment]
Almost done! Only employees_projects has issues

**Comment by CupofJosiah** [comment]
It lags a lot but it works!
